### ISSUE TITLE
gfortran-mp-13: gfortran-compiled binary randomly gives right or wrong outcome

### ISSUE THREAD

**Issue by tpcklaver** [iains/gcc-13-branch#13]
I posted a ticket for an iussue I had found in MacPorts Trac. kencu (Ken) suggested I post it here too, so here it is:

I have a piece of f90 research code that I've compiled on an M2 Pro Apple Silicon Macbook, running macOS Sonoma 14.2.1, Xcode 15.2. I've compiled it with gfortran-mp-13, part of gcc-13, which was installed with MacPorts 2.8.1. 
About half the time the binary produces the right outcome (checked against the same code compiled with gfortran on an Intel Macbook), about half the time it produces a wrong outcome (but always the same wrong outcome, it's wrong but not random noise). This random alternating happens when running the same calculation with the same input in the same working directory with the same binary like 10 times in a row. 
As it works fine with a gfortran-compiled binary on an Intel Macbook, I wonder if the gfortran portion of gcc-13 on Apple Silicon has a problem.
Then again, I also tried with gfortran from Homebrew on my Apple Silicon Macbook, and there I had the exact same problem, sometimes the binary gives the right outcome, sometimes the wrong outcome. I guess this may indicate a more generral problem in gfortran on Apple Silicon, not necessarily the MacPort port of it? 
I attach an archive to this ticket that contains the f90 source code (Aneto, a code to determine elastic interaction energy between periodic defect images), two input files (OUTCAR, input_elast) for a test case, and the binary I compiled. The calculation is run by simply running the binary from a directory containing the two input files. 
If the calculation goes right, the outcome contains a line 
Delta E = 1.65765823 eV 
If it goes wrong, the outcome contains a line 
Delta E = 0.137904249 eV 
If anyone can make sence of this, please let me know. 
[files.zip](https://github.com/iains/gcc-13-branch/files/13941407/files.zip)

**Comment by tpcklaver** [comment]
Small additional info: using the NAG fortran compiler for macOS on Apple Silicon, the unaltered code works correctly.

**Comment by fxcoudert** [comment]
Hi, always nice to see a fellow computational chemist :)

I'm not seeing the source code attached. Without it, it's impossible to debug. But I'm willing to have a look if you can attach the source.

**Comment by tpcklaver** [comment]
Hi [fxcoudert](https://github.com/fxcoudert),

Computational materials scientist rather than computational chemist actually, though I have one paper in J. Phys. Chem. :)

Sorry, that was sloppy of me, not attaching the source code. Attached now with this comment.
[aneto.f90.zip](https://github.com/iains/gcc-13-branch/files/14069323/aneto.f90.zip)

**Comment by fxcoudert** [comment]
Hum, I've found the Aneto software at http://emmanuel.clouet.free.fr/Programs/Aneto/aneto.html however version 1.1 (which you are using) is not available, but they have a version 1.2

On first inspection: I've seen your bug when I compile without optimisation flags. Now I've recompiled with `-O2` and I'm not seeing it anymore. Can you try and report if that helps for your case?

(It's not clear to me if I'm considered a chemist or materials scientist…)

The code is kind of long, so it'll take time to dig into it and figure out what is wrong. I suspect some numerical instability of the code, rather than invalid compilation. In particular, there are several places where the code compares floating-point values with equality, which is never a really good sign in my experience.

**Comment by fxcoudert** [comment]
I'm going to track here my progress (and edit as I go along). When the value is wrong, it is because:
- `Ecorr` at line 1546 is exactly equal to zero
- because the `err` matrix is zero
- because, in `linear_correction_WCai`, the vectors `delta_u_1` and 2 and 3 are all equal to zero (`inv_mat_Ak` on the other hand, is a nonzero diagonal matrix)
- because `u_A1`, `u_A2`, `u_A3` and `u_0` are all zero or very small (`-1.0936777590731058E-297`)
- ok it comes from the top of the `linear_correction_WCai` function. `dR` can have huge, nonsensical values.
- it's because `R_dp` is uninitialized
- `R_dp` is read from the namelist input, but is not present in your input file

**Comment by fxcoudert** [comment]
Conclusion: it's a bug in the Aneto software. `R_dp` should be initialised with a sensible default value, and it's not. You can set it to zero by default doing this:

```
   ! default initialization (namelist)
        
        CVoigt(:,:) = 0.d0 ! GPa
        sigma_res(:,:) = 0.d0 ! GPa
        alat = 1. ! in angstrom 
        nb_div_q = 40 !(TF) 
        n_cut = 40 ! cutting radius in alat units
        A1_ref(:)=0.d0 ; A2_ref(:)=0.d0 ; A3_ref(:)=0.d0 !  alat units
        A1_dp(:)=0.d0 ; A2_dp(:)=0.d0 ; A3_dp(:)=0.d0 !  alat units
        R_dp(:) = 0
```

adding this last line (`R_dp(:) = 0`) in `SUBROUTINE Read_input_EintDP`. It will give you the consistent behaviour you expect.

Why was it working before? Well, it's undefined behaviour, so the code is invalid, and its behaviour depends on what is in the memory at this specific point. Most often the fresh block of memory is zero'ed (and in your case, that was making it work), but you can't rely on that.

PS: if you want to thank me in your next article that uses the software, feel free, I'd definitely appreciate it :)

**Comment by tpcklaver** [comment]
Wow, I was watrching some BBC television and you've been busy in the meantime. :)

First let me confirm that V1.1 gives the same behaviour, i.e. compiling without optimisatiuon randomly gives erroneous output or not, compiled with -O2 it always works right. I fiind this curious. My usual experience is that I need to turn off optimisation to get rid of errors rather than turning optimisation on...

Anyway, I'm not the author of the code, I only use V1.1 because that's the version a colleague of mine passed on to me, along with an input file that ddin't have R_dp in it. I've made a note to add you to the acknowledgements of the paper I'm writing at the momnent, for which I used Aneto. Sorting out this issue is something I'm happy to say 'Thank you' for. :)

**Comment by fxcoudert** [comment]
@tpcklaver for the record, I've emailed the software author with the details, so hopefully they'll issue an update with the fix.

And to be very clear: I would recommend you either use the fixed source code, or fully initialize `R_dp` in your input file. Optimization appears to "fix it" by some chance fluctuation, but it's not reliable or guaranteed.

**Comment by fxcoudert** [comment]
Author was very reactive: new version 1.3 published: http://emmanuel.clouet.free.fr/Programs/Aneto/aneto.html

I think this issue can be closed

**Comment by tpcklaver** [comment]
Indeed, issue can be closed.

Thanks for your very active help in this. :)
