### ISSUE TITLE
D support for PPC

### ISSUE THREAD

**Issue by barracuda156** [iains/gcc-13-branch#2]
Readme says that D does not bootstrap on Darwin 9 Intel, but does on Darwin 10 Intel. What exactly is the issue, if you know? (I remember you have written parts of Libphobos for Darwin PPC, what we need to fix it?)

**Comment by iains** [comment]
there are several issues:
1. the code uses constructs not supported by the Xcode 3.1.4 tools, you need a newer assembler and linker.
2. there are some APIs used in the D runtime missing in 10.5
3. the PPC parts are incomplete (w.r.t. floating point handling, for sure)

1) can be worked around by using at least the XCode-3.2.6 tools, but the impl. is going to be incomplete, and I doubt you can get libphobos to build any more than --with-libphobos-druntime-only, which is quite a limitation.

so, the rest needs time to implement and / or find alternates to the missing APIs.

yes, I did some of the work to support the floating point stuff - but the shape of the D implementation has changed quite a bit (as a result of now using a D compiler written in D and updated upstream library code).  I would expect my prototype patches would need some rework.

Feel free to have a go - but please work on trunk, not a branch since we'd have to apply any changes upstream to trunk and then back port to the Darwin-specific branches as appropriate.

I am going to close this here - since it's an upstream issue not something related to the branches here.

**Comment by barracuda156** [comment]
@iains Is it not planned, not relevant or wrong place to ask?

**Comment by iains** [comment]
this is a question for upstream - I am not the implementor of the D language support - that is coming from an external "upstream".  So you might file a request for enhancement on GCC Bugzilla, but probably the D folks will need your (or someone's) help to implement the Darwin  powerpc support, since they are unlikely to have access to hardware.

I think "is it not planned" is not exactly how to look at it - this is open source; someone can always work on the implementation and/or fixing issues with the current stuff.  As for me, I have more critical areas of Darwin support to work on - that will be useful to all the OS versions and archs.  Of course I do try to build D on 10.5 from time to time - and it can be done with some limitations - so there is a starting point.

**Comment by barracuda156** [comment]
@iains Thank you! 

> Of course I do try to build D on 10.5 from time to time - and it can be done with some limitations - so there is a starting point.

This is indeed inspiring.
